[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "fastapi==0.110.1",
    "motor==3.6.0",
    "numpy==2.4.0",
    "openai==1.99.9",
    "pillow==12.1.0",
    "pydantic==2.12.5",
    "pymongo==4.9.2",
    "python-dotenv==1.2.1",
    "python-multipart==0.0.21",
    "slowapi==0.1.9",
    "uvicorn==0.25.0",
]
